apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apps2cms-ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: apps2cms.dev
    http:
      paths:
        - path: /api/hello
          backend:
            serviceName: auth-api-srv
            servicePort: 4000